---
- name: read file
  hosts: all
  tasks:
  
    - name: capture output of id command
      shell: source /etc/os-release && echo $ID
      register: os_release

    - debug: msg="{{ os_release }}"

    - debug: msg="{{ os_release.stdout }}"
